[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
byteorder = "1"
env_logger = "0.10"
log = "0.4"
pixels = "0.11"
rand = "0.8"
winit = "0.27"
winit_input_helper = "0.13"
